# To run this file run:
# docker-compose -f postgres.docker-compose.yml up -d
version: '3.8'

services:
  basic-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: $$USER_NAME
      POSTGRES_PASSWORD: $$PASSWORD
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres: